// import { TrendingSong } from "./types";

// Default fallback video ID for audio-only playback when no song is selected
// This video will be completely hidden using CSS, only audio will be played to save bandwidth
// Video ID: dg1_0zCosRw - optimized for small quality to minimize data usage
export const FALLBACK_VIDEO_ID = "F074LkX6zr4";

// Alternative lightweight video options for fallback (commented out):
// export const FALLBACK_VIDEO_ID = "dQw4w9WgXcQ"; // Rick Roll - classic lightweight option
// export const FALLBACK_VIDEO_ID = "oHg5SJYRHA0"; // Never Gonna Give You Up - another lightweight choice

// TODO: Consider implementing a dedicated audio player component for audio-only fallback
// This would eliminate the need for YouTube iframe entirely and provide better performance

// Cute messages to display when waiting for a song
export const CUTE_MESSAGES = [
  "Hãy hát cùng Jozo nào! 🎤",
  "Cùng Jozo tạo nên giai điệu tuyệt vời! 🎵",
  "Jozo đang chờ bạn hát cùng! 🎶",
  "Hát cùng Jozo để tạo nên khoảnh khắc đẹp! ✨",
  "Cùng Jozo làm nên âm nhạc! 🎼",
  "Jozo và bạn - cặp đôi hoàn hảo! 💕",
  "Hãy để Jozo nghe giọng hát của bạn! 🎤",
  "Cùng Jozo tạo nên bản nhạc hay! 🎵",
  "Jozo đang sẵn sàng hát cùng bạn! 🎶",
  "Hát cùng Jozo để lan tỏa niềm vui! 😊",
  "Cùng Jozo làm nên những giai điệu đẹp! 🎼",
  "Jozo chờ bạn để cùng tạo nên âm nhạc! 🎤",
  "Hãy hát cùng Jozo và tạo nên kỷ niệm! ✨",
  "Cùng Jozo làm nên những bài hát hay! 🎵",
  "Jozo và bạn - cùng nhau tạo nên âm nhạc! 🎶",
];

// Trending songs list - Chào mừng 80 năm Quốc Khánh 2/9
export const TRENDING_SONGS = [
  {
    title: "Việt Nam Tôi",
    artist: "Jack & K-ICM",
    views: "25.8M",
    genre: "Việt Nam",
    category: "vietnam",
    description: "Tình yêu quê hương đất nước sâu đậm",
  },
  {
    title: "Việt Nam Ơi",
    artist: "Minh Beta",
    views: "18.9M",
    genre: "Việt Nam",
    category: "vietnam",
    description: "Giai điệu tự hào dân tộc",
  },
  {
    title: "Tiến Lên Việt Nam Ơi",
    artist: "Sơn Tùng M-TP",
    views: "32.1M",
    genre: "Việt Nam",
    category: "vietnam",
    description: "Khí thế tiến lên của dân tộc",
  },
  {
    title: "Tự Hào Việt Nam",
    artist: "Nhiều Ca Sĩ Trẻ",
    views: "28.7M",
    genre: "Việt Nam",
    category: "vietnam",
    description: "Tự hào về đất nước Việt Nam",
  },
  {
    title: "Hello Vietnam (Bonjour Vietnam)",
    artist: "Quỳnh Anh / Cover",
    views: "22.4M",
    genre: "Việt Nam",
    category: "vietnam",
    description: "Lời chào Việt Nam bằng tiếng Pháp",
  },
  {
    title: "Niềm Tin Chiến Thắng",
    artist: "Nhiều Ca Sĩ Trẻ",
    views: "19.6M",
    genre: "Việt Nam",
    category: "vietnam",
    description: "Niềm tin vào chiến thắng của dân tộc",
  },
  {
    title: "Đường Đến Ngày Vinh Quang",
    artist: "Bức Tường",
    views: "26.3M",
    genre: "Việt Nam",
    category: "vietnam",
    description: "Con đường dẫn đến vinh quang",
  },
  {
    title: "Nối Vòng Tay Lớn",
    artist: "Trịnh Công Sơn",
    views: "35.2M",
    genre: "Việt Nam",
    category: "vietnam",
    description: "Đoàn kết dân tộc Việt Nam",
  },
  {
    title: "Một Vòng Việt Nam",
    artist: "Nhiều Ca Sĩ",
    views: "21.8M",
    genre: "Việt Nam",
    category: "vietnam",
    description: "Hành trình khám phá Việt Nam",
  },
  {
    title: "Khát Vọng Tuổi Trẻ",
    artist: "Nhiều Ca Sĩ",
    views: "24.5M",
    genre: "Việt Nam",
    category: "vietnam",
    description: "Khát vọng của thế hệ trẻ Việt Nam",
  },
  {
    title: "Việt Nam Muôn Màu",
    artist: "Nhiều Ca Sĩ",
    views: "17.9M",
    genre: "Việt Nam",
    category: "vietnam",
    description: "Việt Nam đa dạng và phong phú",
  },
  {
    title: "Tổ Quốc Gọi Tên Mình",
    artist: "Nhiều Ca Sĩ",
    views: "29.1M",
    genre: "Việt Nam",
    category: "vietnam",
    description: "Tiếng gọi thiêng liêng của Tổ quốc",
  },
  {
    title: "Đường Chúng Ta Đi",
    artist: "Nhiều Ca Sĩ",
    views: "20.7M",
    genre: "Việt Nam",
    category: "vietnam",
    description: "Con đường chung của dân tộc",
  },
  {
    title: "Việt Nam Tự Hào Tiếp Bước Tương Lai",
    artist: "Nhiều Ca Sĩ",
    views: "23.4M",
    genre: "Việt Nam",
    category: "vietnam",
    description: "Tự hào bước vào tương lai",
  },
  {
    title: "Con Đường Ta Chọn",
    artist: "Nhiều Ca Sĩ",
    views: "18.3M",
    genre: "Việt Nam",
    category: "vietnam",
    description: "Lựa chọn con đường đúng đắn",
  },
  {
    title: "Việt Nam – Hướng Về Tương Lai",
    artist: "Nhiều Ca Sĩ",
    views: "25.9M",
    genre: "Việt Nam",
    category: "vietnam",
    description: "Hướng về tương lai tươi sáng",
  },
  {
    title: "Cùng Bước Tới Vinh Quang",
    artist: "Nhiều Ca Sĩ",
    views: "22.1M",
    genre: "Việt Nam",
    category: "vietnam",
    description: "Cùng nhau tiến tới vinh quang",
  },
  {
    title: "Bước Đi Không Dừng Lại",
    artist: "Nhiều Ca Sĩ",
    views: "19.8M",
    genre: "Việt Nam",
    category: "vietnam",
    description: "Kiên trì bước đi không ngừng",
  },
  {
    title: "Giai Điệu Tổ Quốc",
    artist: "Tạ Quang Thắng",
    views: "27.6M",
    genre: "Việt Nam",
    category: "vietnam",
    description: "Giai điệu thiêng liêng của Tổ quốc",
  },
  {
    title: "Tự Hào Tổ Quốc Tôi",
    artist: "Hồ Ngọc Hà, Văn Mai Hương, Noo, Isaac, Đông Nhi",
    views: "31.4M",
    genre: "Việt Nam",
    category: "vietnam",
    description: "Tự hào về Tổ quốc Việt Nam",
  },
  {
    title: "Tổ Quốc Gọi Tên Mình",
    artist: "Quang Dũng, Tạ Quang Thắng",
    views: "26.8M",
    genre: "Việt Nam",
    category: "vietnam",
    description: "Tiếng gọi thiêng liêng của Tổ quốc",
  },
  {
    title: "Nơi Đảo Xa",
    artist: "Trần Tiến",
    views: "24.2M",
    genre: "Việt Nam",
    category: "vietnam",
    description: "Tình yêu biển đảo quê hương",
  },
  {
    title: "Quê Hương",
    artist: "Giáp Văn Thạch",
    views: "21.5M",
    genre: "Việt Nam",
    category: "vietnam",
    description: "Tình yêu quê hương sâu đậm",
  },
  {
    title: "Viết Tiếp Câu Chuyện Tương Lai",
    artist: "Nguyễn Văn Chung",
    views: "18.7M",
    genre: "Việt Nam",
    category: "vietnam",
    description: "Viết tiếp câu chuyện tương lai",
  },
  {
    title: "Việt Nam – Tự Hào Tiếp Bước Tương Lai",
    artist: "Tùng Dương",
    views: "23.9M",
    genre: "Việt Nam",
    category: "vietnam",
    description: "Tự hào tiếp bước vào tương lai",
  },
];
